database:
  host: localhost
  port: 5432
  user: user
  password: password
  name: auth_db
  sslmode: disable

jwt:
  secret: super-secret-key

memcached:
  host: localhost
  port: 11211

server:
  port: 8080
